apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qcs-gitops-environments
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/qlik-trial/gitops-environments
        revision: main
        requeueAfterSeconds: 90
        files:
          - path: components/bonjour-world/qlik-cloud-services-int-env/conf.yaml
  template:
    metadata:
      name: "{{index .path.segments 1}}"
      annotations:
        notifications.argoproj.io/subscribe.on-deployed-version.app-deployed-webhook: ""
        notifications.argoproj.io/subscribe.on-deployed-revision.app-deployed-webhook: ""
        notifications.argoproj.io/subscribe.on-sync-failed.app-deployed-webhook: ""
        notifications.argoproj.io/subscribe.on-health-degraded.app-deployed-webhook: ""
        notifications.argoproj.io/subscribe.on-template-failed.app-deployed-webhook: ""
        notifications.argoproj.io/subscribe.on-template-failed-slack.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-deployed-version.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-deployed-revision.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-created.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-deleted.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-health-degraded.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-sync-failed.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: '{{dig "slackNotifyChannel" "argocd-qcs-int-monitoring" .}}'
        pipeline.qlik.com/version: "{{.version}}"
        pipeline.qlik.com/version-override: "{{.versionOverride}}"
        pipeline.qlik.com/heo-revision: "{{.heoRevision}}"
        pipeline.qlik.com/heo-revision-override: "{{.heoRevisionOverride}}"
        pipeline.qlik.com/environment: "qlik-cloud-services-int-env"
      labels:
        app.kubernetes.io/version: "{{if .versionOverride}}{{.versionOverride}}{{else}}{{.version}}{{end}}"
        app.kubernetes.io/heo-revision: "{{if .heoRevisionOverride}}{{.heoRevisionOverride}}{{else}}{{.heoRevision}}{{end}}"
    spec:
      project: qcs
      source:
        repoURL: https://github.com/qlik-trial/helm-environment-overrides
        targetRevision: "{{if .heoRevisionOverride}}{{.heoRevisionOverride}}{{else}}{{.heoRevision}}{{end}}"
        path: "{{.heoRoot}}/{{index .path.segments 1}}"
      destination:
        server: eks-dev
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
